### ISSUE TITLE
Question regarding Terraform CNI route table

### ISSUE THREAD

**Issue by dkirrane** [jamesbannan/pluralsight#8]
@jamesbannan 

Following the course. Just want to know what the `azurerm_route_table` and the `VirtualAppliance` route are needed for? Is this a AKS CNI requirement?

https://github.com/jamesbannan/pluralsight/blob/0ca3060bb51be662f6bb54a58a8aed7e93d5a6ec/azure-devops-kubernetes-infrastructure/module-terraform/terraform/azure-network.tf#L22

**Comment by jamesbannan** [comment]
@dkirrane Thanks for raising the issue - yes, it's a requirement when the AKS cluster is deployed using Advanced networking, which is where the pods have their own IP addresses drawn from the virtual network subnet, rather than from an internal pod CIDR range.

There's an example in the Hashicorp repo: https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/examples/kubernetes/advanced-networking/main.tf
